### ISSUE TITLE
Force Install on Login

### ISSUE THREAD

**Issue by benstrattonwoodward** [hjuutilainen/munkiadmin#137]
I'm new to Munki and just setting up my first client. I am having trouble finding how to set up "force install on login" so that things like office updates and installs take while the Microsoft apps are closed.
Everything else seems to work fine but I think I may have missed some code in the client set up. 
Do need to be setting something up in the login so that the Mac knows to install at login?

I have a ManagedInstalls.plist that looks like this:

`<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>AppleSoftwareUpdatesOnly</key>
    <false/>
    <key>ClientIdentifier</key>
    <string>firsttestmanifest</string>
    <key>FollowHTTPRedirects</key>
    <string>none</string>
    <key>InstallAppleSoftwareUpdates</key>
    <false/>
    <key>LastCheckDate</key>
    <date>2016-10-19T16:35:24Z</date>
    <key>LastCheckResult</key>
    <integer>1</integer>
    <key>LogFile</key>
    <string>/Library/Managed Installs/Logs/ManagedSoftwareUpdate.log</string>
    <key>LogToSyslog</key>
    <false/>
    <key>LoggingLevel</key>
    <integer>1</integer>
    <key>ManagedInstallDir</key>
    <string>/Library/Managed Installs</string>
    <key>PackageVerificationMode</key>
    <string>hash</string>
    <key>PendingUpdateCount</key>
    <integer>1</integer>
    <key>SoftwareRepoURL</key>
    <string>http://munki.exposure.net</string>
    <key>SuppressAutoInstall</key>
    <false/>
    <key>UseClientCertificate</key>
    <false/>
</dict>
</plist>`

**Comment by hjuutilainen** [comment]
If I'm understanding this correctly you're looking for the `unattended_install` key which will cause items to be installed silently in the background if none of the blocking applications are running (for example, update Office if Word or Excel or other MS apps are not running). This is something that needs to be set in the pkginfo file in your munki repository instead of the client settings.

Here's a screenshot of my Office 2016 pkginfo with the correct setting highlighted:
<img width="946" alt="screen shot 2016-10-19 at 20 50 51" src="https://cloud.githubusercontent.com/assets/19357/19530984/b060fa50-963e-11e6-92c2-5ad55965bfd5.png">

There's no setting in Munki to install things specifically when a user logs in. There's usually no need for this, it's best to let Munki run in the background and do installs automatically.

**Comment by benstrattonwoodward** [comment]
Huge thanks ☺



Ben Stratton‑Woodward           Head of IT: Exposure Group

22-23 Little Portland Street
London, W1W 8BU<https://www.google.co.uk/maps/place/22-23+Little+Portland+St,+Fitzrovia,+London+W1W+8BU/@51.5171316,-0.1406746,17z/data=!3m1!4b1!4m2!3m1!1s0x48761b2a83937681:0xcbcfc75e2e7052ca>

T       +442079077143<tel:+442079077143>

M       +44 7932688617<tel:+44%207932688617>

www.exposure.net<http://www.exposure.net>

[Instagram]<https://instagram.com/exposurelondon>
See more @exposurelondon<https://instagram.com/exposurelondon>
