### ISSUE TITLE
Setting Force Install After Date Displays in Local but Saves in GMT

### ISSUE THREAD

**Issue by WardsParadox** [hjuutilainen/munkiadmin#150]
I live in Mountain time zone here in the states, I noticed that when setting the Force Install After date, while it did display it in local time (09/19/2017 04:52 PM), it saved it in a time converted to GMT 6 hours ahead (09/19/2017 11:00 PM) Reloading this also showed that it was still in local time. MSC runs based on Local Time, not GMT so this should probably be fixed.

Again thank you for making such an amazing software. I will try and see if I can find the code that is causing this. To help narrow it down.

**Comment by WardsParadox** [comment]
This line: `NSTimeZone *timeZoneUTC = [NSTimeZone timeZoneWithAbbreviation:@"UTC"];`
Maybe the cause, could be changed to:
`NSTimeZone *timeZoneUTC = [NSTimeZone localTimeZone];` ?

Here:
https://github.com/hjuutilainen/munkiadmin/blob/32637de3226ad0c9400e4c05e8134bd243ef465f/MunkiAdmin/UI%20Controllers/MAAdvancedPackageEditor.m#L51

**Comment by flammable** [comment]
Confirming that I'm observing the same issue in Eastern time (Zack and I discussed this in Slack).  I set a pkg to force install by 6 PM in MunkiAdmin, and the pkginfo indicated that the installation time would be set to 22:00 (10 PM).

**Comment by hjuutilainen** [comment]
Thanks for reporting this.

The date picker UI component needs to specifically use UTC (since the date in pkginfo is UTC) to avoid displaying the date in some other time zone. It was previously enough to only set the date picker time zone but evidently the whole app default time zone needs to be UTC.

Could you try this test build to see if it displays and saves the date correctly:
https://www.dropbox.com/s/q87ml5nj3a0mw9j/MunkiAdmin-1.5.1-2-g8818d34.dmg?dl=0

**Comment by WardsParadox** [comment]
That fixes it. Thanks!
