### ISSUE TITLE
Munkiadmin crashes in Manifest view

### ISSUE THREAD

**Issue by fridomac** [hjuutilainen/munkiadmin#88]
Hello! 
First: A huge thanks for MunkiAdmin! It really is a great help in day-to-day use....

Ever since Munkiadmin 1.2, it crashes on me in Manifest view. If I click on "Recently Modified", the listing does not change (neither does it when clicking on Machine/Group/Profile Manifests), it crashes. I enabled debug and put the debug log here: https://gist.github.com/fridomac/069533b859d091ac7094. I did not see anything in the log right before the crash, maybe you do.

Bye, Frido.

**Comment by hjuutilainen** [comment]
Thanks for reporting. Are you using the latest version (1.2.2)?

**Comment by fridomac** [comment]
Yes, it is 1.2.2.

**Comment by hjuutilainen** [comment]
Downloaded the log, thanks. You can disable the debug logging for now since it slows MunkiAdmin down considerably and perhaps delete the gist if you want (it contains a lot of information).

The only suspicious thing I found in the log are these lines:

    2015/08/19 14:31:06:710  mac1497: linking managed_update object AdobeInDesignCS6
    2015/08/19 14:31:06:727  mac1497: Error: Could not link managed_update object 29 --> Name: AdobeInDesignCS6

It means that the manifest `mac1497` includes a managed_update string `AdobeInDesignCS6` but there is no package in your repo with that name. Could you try removing that reference with a text editor and try running MunkiAdmin again.

Does MunkiAdmin show up as "Not responding" if you open Activity Monitor.app? If it does, could you take a sample and post it. To take a sample, select MunkiAdmin in the process list and choose View -> Sample Process command.

**Comment by fridomac** [comment]
So, I am back at work, removed the mac1497 manifest altogether (was an old machine anyway), but it crashes just the same (I am running 10.10.5). Tried it on another machine running 10.9.5, all was functioning perfectly there. Will try on a freshly installed machine again, maybe something is wonky on my install. Bye, Frido.

**Comment by morgrowe** [comment]
Not sure if this helps, but MunkiAdmin kept crashing for me when attempting to click on 'Recently Modified' filter in the sidebar under the 'Manifests' section since 1.2, too. This also happened on version 1.2.2 and version 1.3.

However, after three crashes on version 1.3 (just updated from version 1.2.2 this morning), I opened MunkiAdmin to find that not only did it not crash when clicking on the 'Recently Modified' filter in the sidebar, the 'Categories' and 'Directories' sections were populated with information as well.

![munki-1 3 0-error](https://cloud.githubusercontent.com/assets/4726315/9599597/fd140a20-508c-11e5-85d0-74d754c303ec.jpg)

Whilst the application was crashing the sections annotated using the arrows were empty. I guess MunkiAdmin was trying to gather information from the manifests in my repo to create those filters, which if interrupted caused a crash? Not too sure.

Also wanted to thank you for all of your hard work on MunkiAdmin, it truly offers a great way to manage a Munki repo!

**Comment by hjuutilainen** [comment]
The manifests view should be a lot more robust in the latest release (1.4.1). Are you still seeing these?

**Comment by morgrowe** [comment]
Yes, it's been working perfectly since 1.4's release for me. Thanks!

**Comment by fridomac** [comment]
Same here, working great since 1.4.
Thank you again!
