### ISSUE TITLE
View packages by catalog they're assigned to

### ISSUE THREAD

**Issue by mkuron** [hjuutilainen/munkiadmin#91]
There should be a way to filter the packages list in order to see all packages assigned to a specific catalog. For example, I'd like to see all packages in my _testing_ catalog so that I can easily go through them and promote them to my _production_ catalog.

A **Catalogs** section in the sidebar would be nice for this. In my case, an entry for each catalog would be sufficient there because I remove my packages from the _testing_ catalog when I add them to the _production_ catalog. Other people might have items in multiple catalogs, so for them it might be more useful to have one entry in the sidebar per combination of catalogs used.

**Comment by arubdesu** [comment]
I agree that munkiAdmin should be good at this. Just chiming in to explain how I end up accomplishing a promotion workflow: I don't even filter by last 30 days, but sort the packages list by date created. Then I go back to the date that I should have been promoting things to the production 'branch/track' from, and work backwards, adding packages as I go. 

I wish I could have that date-created-sort stick as the default view. I know that some other people's workflow is to only have things in one catalog at the time, so it still needs to be flexible to support them as well.

**Comment by hjuutilainen** [comment]
Thanks for creating an issue for this. I agree with both of you. The packages-to-catalogs workflow is something I'm going to focus on in the near future (now that the manifests UI has been refreshed). There are a number of things I'm already planning:

- Catalogs should have their own column in packages list. 
- The sidebar should have a (user configurable) catalogs section. 
- There should be some kind of keyboard shortcut functionality for modifying the catalogs without the need to open the editor or right click menu. 
- The old catalogs view will be deprecated when the catalogs are easier to edit right in the packages view.

**Comment by arubdesu** [comment]
While thinking over what a 'refined'/next gen Catalog tab/view would look like, (assuming this change doesn't eliminate its need altogether,) it seems like a good idea may be to take a cue from Margarita: filter/hide pkgs already promoted to prod, or are already included across all catalogs. I'll leave it at that, as I have no insight into the changes to moving parts/plumbing required for the initial steps you already had in mind... but while we're on the topic I also wanted to bring up...
I personally revise and leave around a lot of bootstrapping or testing(e.g. rapidly iterated versions of munki) pkgs that even my testing clients never see, since I don't need to alter that state of the machine once deployed or potentially annoy testing by pushing too many updates. So being able to filter out/wade through only the pkgs that are applicable for the full promotion workflow would also be dreamy, if that seems like a common case worth taking into consideration.

**Comment by mkuron** [comment]
To make it generic enough to work with all described promotion workflows, we'd probably need custom smart groups in the sidebar. I believe all the stuff currently in the sidebar is already filtered based on predicates, so this should actually be reasonably easy to add.

**Comment by hjuutilainen** [comment]
Something like this is coming to the next release soon. I think this should help until I get configurable sidebar items done.
<img width="745" alt="screen shot 2015-10-17 at 21 14 38" src="https://cloud.githubusercontent.com/assets/19357/10560448/596fe626-7514-11e5-8a2a-8f0b91382c40.png">

**Comment by arubdesu** [comment]
👍Looking good!

**Comment by hjuutilainen** [comment]
Catalogs column is now available in version 1.4.0. It's hidden by default but can be enabled by right-clicking the table view header:
![screen shot 2015-10-24 at 21 13 24](https://cloud.githubusercontent.com/assets/19357/10711956/204a96f4-7a94-11e5-8ab3-d4a11143fb20.png)

**Comment by mkuron** [comment]
Great, thanks!

**Comment by hjuutilainen** [comment]
Closing this since it is included in released version. Will keep refining the catalog workflow in future versions too.
